on:
  schedule:
    - cron: '28 21 * * *'
  workflow_dispatch:

jobs:
  pull:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - run: python3 gen.py
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          commit_options: '--amend --no-edit'
          push_options: '--force'
          skip_fetch: true
